using System;
using System.Collections.Generic;
using Godot;

namespace MarchingTrianglesTerrain.addons.marchingTriangles.triangulation;

/// <summary>
/// Utility class for various triangle computations in 3D space
/// </summary>
public static class TriangleUtils
{

    public static Vector3 GetNormal(Vector3[] tri)
    {
        return (tri[1] - tri[0]).Cross(tri[2] - tri[0]).Normalized();
    }
    public static bool CoplanarTrianglesIntersect(Vector3[] tri1, Vector3[] tri2)
    {
        return CoplanarTrianglesIntersect(
            tri1[0],tri1[1],tri1[2],
            tri2[0],tri2[1],tri2[2],
            (tri1[1]-tri1[0]).Cross(tri1[2]-tri1[0]));
    }
    private static bool CoplanarTrianglesIntersect(
        Vector3 t1V0, Vector3 t1V1, Vector3 t1V2,
        Vector3 t2V0, Vector3 t2V1, Vector3 t2V2, Vector3 normal)
    {
        // Project 3D coplanar triangles onto a 2D plane based on the dominant normal axis
        Vector2 p10, p11, p12, p20, p21, p22;
        if (MathF.Abs(normal.X) > MathF.Abs(normal.Y) && MathF.Abs(normal.X) > MathF.Abs(normal.Z))
        {
            p10 = new Vector2(t1V0.Y, t1V0.Z);
            p11 = new Vector2(t1V1.Y, t1V1.Z);
            p12 = new Vector2(t1V2.Y, t1V2.Z);
            p20 = new Vector2(t2V0.Y, t2V0.Z);
            p21 = new Vector2(t2V1.Y, t2V1.Z);
            p22 = new Vector2(t2V2.Y, t2V2.Z);
        }
        else if (MathF.Abs(normal.Y) > MathF.Abs(normal.Z))
        {
            p10 = new Vector2(t1V0.X, t1V0.Z);
            p11 = new Vector2(t1V1.X, t1V1.Z);
            p12 = new Vector2(t1V2.X, t1V2.Z);
            p20 = new Vector2(t2V0.X, t2V0.Z);
            p21 = new Vector2(t2V1.X, t2V1.Z);
            p22 = new Vector2(t2V2.X, t2V2.Z);
        }
        else
        {
            p10 = new Vector2(t1V0.X, t1V0.Y);
            p11 = new Vector2(t1V1.X, t1V1.Y);
            p12 = new Vector2(t1V2.X, t1V2.Y);
            p20 = new Vector2(t2V0.X, t2V0.Y);
            p21 = new Vector2(t2V1.X, t2V1.Y);
            p22 = new Vector2(t2V2.X, t2V2.Y);
        }

        // Perform 2D SAT or 2D overlap check
        return Test2DTriangleIntersection(p10, p11, p12, p20, p21, p22);
    }

    private static bool Test2DTriangleIntersection(
        Vector2 a0, Vector2 a1, Vector2 a2,
        Vector2 b0, Vector2 b1, Vector2 b2)
    {
        Vector2[] triA = [a0, a1, a2];
        Vector2[] triB = [b0, b1, b2];

        // Test separation axes generated by edges of Triangle A and Triangle B
        if (IsSeparated2D(triA, triB)) return false;
        if (IsSeparated2D(triB, triA)) return false;

        return true;
    }

    private static bool IsSeparated2D(Vector2[] triA, Vector2[] triB)
    {
        for (int i = 0; i < 3; i++)
        {
            Vector2 edge = triA[(i + 1) % 3] - triA[i];
            Vector2 normal = new Vector2(-edge.Y, edge.X); // Perpendicular axis

            Project2D(triA, normal, out float minA, out float maxA);
            Project2D(triB, normal, out float minB, out float maxB);

            if (maxA < minB || maxB < minA)
                return true; // Found a separating axis
        }

        return false;
    }

    private static void Project2D(Vector2[] vertices, Vector2 axis, out float min, out float max)
    {
        min = float.MaxValue;
        max = float.MinValue;
        for (int i = 0; i < vertices.Length; i++)
        {
            float projection = vertices[i].Dot(axis);
            if (projection < min) min = projection;
            if (projection > max) max = projection;
        }
    }
}


public class FloatArrayComparer : IEqualityComparer<float[]>, IComparer<float[]>
{
    public FloatArrayComparer(double epsilon)
    {
        this._epsilon = epsilon;
    }

    private double _epsilon;

    public bool Equals(float[]? x, float[]? y)
    {
        if (x == null || y == null) return false;
        if (x.Length != y.Length)
            return false;
        for (int i = 0; i < x.Length; i++)
        {
            if (Math.Abs(x[i] - y[i]) > _epsilon)
            {
                return false;
            }
        }

        return true;
    }

    public int GetHashCode(float[] obj)
    {
        var v = 31;
        for (int i = 0; i < obj.Length; i++)
        {
            // Proximity of hashcode so that buckets are similar for similar points 
            v = v * 31 * (int)(100 * (obj[i])) + 7;
        }

        return v;
    }

    public int Compare(float[]? x, float[]? y)
    {
        if (x == null && y == null) return 0;
        if (x == null) return -1;
        if (y == null) return 1;

        return x.Equals(y) ? 0 : x.GetHashCode() - y.GetHashCode();
    }
}