# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 9.0.x
        
    - name: No .NET Telemetry
      run: echo DOTNET_CLI_TELEMETRY_OPTOUT=1 >> $GITHUB_ENV
        
    - name: Restore dependencies
      run: dotnet restore
    - uses: chickensoft-games/setup-godot@v2
      name: Setup Godot
      with:
        # Version must include major, minor, and patch, and be >= 4.0.0
        # Pre-release label is optional.
        version: 4.6.2 
        # Use .NET-enabled version of Godot (the default is also true).
        use-dotnet: true
        # Include the Godot Export Templates (the default is false).
        include-templates: false

    - name: Verify Setup
      run: |
        echo GODOT_BIN=$GODOT >> $GITHUB_ENV
        dotnet --version
        godot --version

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test ./UnitTests/UnitTests.csproj --no-build --verbosity normal
    - name: Integration Tests
      run: dotnet test ./UnitTests4Godot/UnitTests4Godot.csproj --no-build --verbosity normal --settings ./.runsettings
